### ISSUE TITLE
代码解惑

### ISSUE THREAD

**Issue by liu-y-d** [ainilili/ratel#103]
package org.nico.ratel.landlords.entity;

import org.nico.ratel.landlords.enums.PokerLevel;
import org.nico.ratel.landlords.enums.PokerType;

/**
 * Poke, with {@link PokerLevel} and {@link PokerType}
 *
 * @author nico
 */
public class Poker {

	……

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((level == null) ? 0 : level.hashCode());
		result = prime * result + ((type == null) ? 0 : type.hashCode());
		return result;
	}

	……

}

上述代码中，我尝试理解Poker类的HashCode需要将属性level和type的HashCode结合起来，但是并不理解 31 这个特殊值，希望能帮我解惑一下

**Comment by BenanaH** [comment]
扰动，提高计算效率并减少哈希冲突的可能性，31可是个好东西：https://stackoverflow.com/questions/299304/why-does-javas-hashcode-in-string-use-31-as-a-multiplier

**Comment by liu-y-d** [comment]
@BenanaH 谢谢谢谢🍭
