### ISSUE TITLE
添加一些特定指令使得玩家之间可以互动。

### ISSUE THREAD

**Issue by YiMo1** [ainilili/ratel#115]
能否给予玩家一些特殊指定，就像是MC那样。

玩家可以使用一些特定指令对其它玩家发起互动，比如丢番茄等。

就像这样：`tomato player1`、`egg player2`。

系统接收到消息后，所有玩家（包括观众）会在命令行输出提示，就像这样：`player1 向 player2 丢了一个番茄`。

然后在这句提示下，被互动的玩家会出现一个用字符绘画的番茄或者鸡蛋图案。

可能存在的问题就是当玩家恶意去刷指令，被互动的玩家终端会被恶意刷屏。

不知道作者认为这个想法怎么样？以及实现难度如何？

**Comment by ainilili** [comment]
非出牌回合，命令行模式下没办法做更多交互，目前只允许出牌回合发言，这个时候再丢道具也没啥意义了

**Comment by YiMo1** [comment]
好吧
