### ISSUE TITLE
关于内容的排版

### ISSUE THREAD

**Issue by fgksgf** [ainilili/ratel#15]
1. 显示房间列表时，如果房主名称过长会导致列表内容错位，建议对昵称进行一定限制。
![jietu20181115-093835](https://user-images.githubusercontent.com/26627380/48525623-cb2e3200-e8bf-11e8-8236-8eab1b3c556f.jpg)

2. 可以考虑使用命令行着色库让一些关键信息能够醒目地输出。

**Comment by ainilili** [comment]
下个版本会对昵称长度限制，命令行如果加色库的话就违反了初衷，划水应该低调点

**Comment by abbychau** [comment]
這兒用`printf` 制表比用`\t` 好

**Comment by bandhan25** [comment]
> The next version will limit the nickname length.

How much max length (max number of characters) should be kept ? Can empty nickname be entered ?

**Comment by ainilili** [comment]
> > The next version will limit the nickname length.
> 
> How much max length (max number of characters) should be allowed ? Can empty nickname be entered ?

Merge complete, I will also verify nickname at server!
