### ISSUE TITLE
Room List ：如果用户名过长，导致位置错乱

### ISSUE THREAD

**Issue by zhanggc** [ainilili/ratel#19]
Room List ：如果用户名过长，导致位置错乱

![image](https://user-images.githubusercontent.com/1655136/48543567-c8056700-e8fc-11e8-9eb7-7db46c8e497a.png)

**Comment by ainilili** [comment]
> Room List ：如果用户名过长，导致位置错乱
> 
> ![image](https://user-images.githubusercontent.com/1655136/48543567-c8056700-e8fc-11e8-9eb7-7db46c8e497a.png)

It already be resolved in ``dev-1.1.0`` branch
