### ISSUE TITLE
ClientSide id可能冲突

### ISSUE THREAD

**Issue by xkenmon** [ainilili/ratel#27]
https://github.com/ainilili/ratel/blob/17309154fc00cefe99086409c9bfffd1729dcd6d/landlords-server/src/main/java/org/nico/ratel/landlords/server/handler/TransferHandler.java#L81
使用客户端连接端口号作为id有很大的可能产生冲突

**Comment by ainilili** [comment]
问题已确认，感谢指出！在大规模客户端连接或者客户端指定port的情况下很容易引发id冲突的问题😀
