### ISSUE TITLE
创建房间后结束进程，再次连接进入该房间，上次退出的用户仍在房间内

### ISSUE THREAD

**Issue by Hyseen** [ainilili/ratel#29]
![image](https://user-images.githubusercontent.com/17402489/51239698-0975c980-19b5-11e9-818a-7fe23e9d9962.png)
如上图所示，该房间内的3个用户全都是我自己创建的。
复现步骤：

1. 创建一个房间，然后使用 `Control` + `C` 结束客户端进程
2. 重新连接服务器，进入刚才创建的房间，然后使用`Control` + `C` 结束客户端进程
3. 重新连接服务器，进入刚才创建的房间，开始游戏，然后再使用 `Control` + `C` 结束客户端进程

**Comment by ainilili** [comment]
非常感谢。

Linux系统下的Ctrl+C并不能通知套接字的关闭，为了处理这个问题，Ratel采用超时策略，默认房间创建后100s没有任何操作将会自动关闭房间。

如果您有好的解决方案，非常希望能分享给我们😆

**Comment by doveeeee** [comment]
复写 `handlerRemoved` 方法可以捕获socket关闭 在`wsl`与`linux`环境中通过测试

``` java 
public class TransferHandler extends ChannelInboundHandlerAdapter {

    @Override
    public void handlerRemoved(ChannelHandlerContext ctx) {
        ClientSide client = ServerContains.CLIENT_SIDE_MAP.get(getId(ctx.channel()));
        SimplePrinter.serverLog("client " + client.getId() +"(" + client.getNickname() + ") disconnected");
        clientOfflineEvent(ctx.channel());
        ctx.channel().close();
    }
    ......
}
```
