### ISSUE TITLE
请教 js 如何连接 server？

### ISSUE THREAD

**Issue by ghost** [ainilili/ratel#34]
我正在使用 js 编写一个客户端程序，请问我该使用什么协议和服务端进行通信呢？http？websocket？还是什么？

**Comment by ainilili** [comment]
网络协议是tcp，数据传输走``protocol buffer``协议，所以你需要使用nodejs去实现客户端和服务端的通讯 xD

**Comment by zmrenwu** [comment]
评估来看，让服务端支持 websocket 协议容易吗？修改量大不大？

**Comment by ainilili** [comment]
> 评估来看，让服务端支持 websocket 协议容易吗？修改量大不大？

将指令解析层替换为websocket协议即可

**Comment by ainilili** [comment]
已经支持websocket协议，js可以对接了
