### ISSUE TITLE
花色无法显示

### ISSUE THREAD

**Issue by penglingfeng1995** [ainilili/ratel#52]
[DOWN] robot_1     surplus 14 [LANDLORD]
It's your turn to play, your pokers are as follows:
┌──┐──┐──┐──┐──┐──┐──┐──┐──┐──┐──┐──┐──┐──┐──┐──┐──┐
│3 |4 |5 |6 |7 |8 |9 |10|10|J |Q |Q |K |K |A |2 |S |
│? |? |? |? |? |? |? |? |? |? |? |? |? |? |? |? |  |
└──┘──┘──┘──┘──┘──┘──┘──┘──┘──┘──┘──┘──┘──┘──┘──┘──┘
Please enter the card you came up with (enter [EXIT] to exit current room, enter [PASS] to jump current round)

idea 的控制台中无法显示花色

**Comment by abbychau** [comment]
改改控制台的字體，要支持花色字符的才能顯示

**Comment by lbj4312** [comment]
怎么改
