### ISSUE TITLE
建议：PVP对战结束后不用重新C房

### ISSUE THREAD

**Issue by luoyang14z7** [ainilili/ratel#64]
1.取消对局结束后解散房间
2.增加玩家对战计分器
（地主赢了2分 农民1分 炸弹春天翻倍）

**Comment by EldersJavas** [comment]
我借楼也说个建议

服务器可以记录IP、网名，保存在服务器里，这样也可以和楼主建议的积分器相匹配，也不用每次登录都输网名
（<del>之后做欢乐豆充值功能</del>）

**Comment by ainilili** [comment]
以支持，请下载[v1.3.0](https://github.com/ainilili/ratel/releases/tag/v1.3.0)版本
