### ISSUE TITLE
等待他人出牌阶段，需要一定时间限制

### ISSUE THREAD

**Issue by MyWikey** [ainilili/ratel#8]
等待时间太长，用户体验不好

**Comment by ainilili** [comment]
这也是我最初的考虑，不过控制台版本不方便增加计时提醒，输入阻塞流会阻塞计时的显示，异步显示计时又会阻碍用户出牌，所以在思考以其他方式弥补，如果有好的想法可以分享给我们

**Comment by abbychau** [comment]
我覺得反正日後都要加賬戶穩定度去防止人隨意斷線。超過一定時間不出牌慢慢扣穩定度，直到扣光或者到某個常數就把它強斷就可以了。

**Comment by ainilili** [comment]
如果对方在一定时间内未出牌将会替换为人机
