### ISSUE TITLE
1.40版本 创建房间 自动解散时间太短    打完牌 房间自动解散 

### ISSUE THREAD

**Issue by CryanNing** [ainilili/ratel#83]
希望 超时时间调个几分钟  队友还没来房间就解散了   还有就是  打完牌  房间也自动解散了  。。又要重新创建房间 。。。又或者是 后台有设置吗 ？设置的命令是什么？主页的设置 选中 自动回到上一级没有用。

**Comment by ainilili** [comment]
可以试试新版，http://rtol.isnico.com



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年02月24日 11:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [ainilili/ratel] 1.40版本 创建房间 自动解散时间太短    打完牌 房间自动解散  (Issue #83) |

Closed #83.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
